name: Deploy
run-name: Deploy 🚀
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: https://github.com/docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Log in to Docker Registry
        uses: https://github.com/docker/login-action@v2
        with:
          registry: code.db.cafe
          username: pauloo27
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          file: Dockerfile
          context: .
          push: true
          tags: code.db.cafe/pauloo27/me:${{ github.sha }},code.db.cafe/pauloo27/me:${{ github.ref_name }}

      - name: Rollout deployment using k7z
        uses: https://code.db.cafe/actions/k7z-rollout@master
        with:
          base_url: https://k7z.db.cafe
          project_id: me
          secret: ${{ secrets.K7Z_SECRET }}
