version: v0

runs:
  - name: Portfolio

    # Build
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: node:14
        steps:
          - clone:
          - restore_cache:
              keys:
                - node_modules-cache-{{ md5sum "yarn.lock" }}-{{ year }}-{{ month }}
              dest_dir: /root/project/node_modules
          - run: yarn install
          - run: yarn build
          - save_cache:
              key: node_modules-cache-{{ md5sum "yarn.lock" }}-{{ year }}-{{ month }}
              contents:
                - source_dir: /root/project/node_modules
                  paths: 
                    - '**'
          - save_to_workspace:
              contents:
                - source_dir: /root/project/
                  dest_dir: /root/project/
                  paths:
                    - '**'

      # Deploy (when the branch is master)
      - name: deploy
        when:
          branch: master
        environment:
          REGISTRY_URL:
            from_variable: registry-url
          REGISTRY_TOKEN:
            from_variable: registry-token
          REGISTRY_IMAGE:
            from_variable: registry-image
        depends:
          - build
        runtime:
          containers:
            - image: gcr.io/kaniko-project/executor:debug
        shell: /busybox/sh
        steps:
          - restore_workspace:
              dest_dir: /
          - run: mv /root/project/* /workspace/
          - run:
              name: generate docker config
              command: |
                cat << EOF > /kaniko/.docker/config.json
                {
                  "auths": {
                    "$REGISTRY_URL": { "auth" : "$REGISTRY_TOKEN" }
                  }
                }
                EOF
          - run:
              name: build docker image
              command: /kaniko/executor --destination $REGISTRY_URL/$REGISTRY_IMAGE --force
